version: '3'
services:
  go:
    build: ./go/
    command: bash -c "tail -f /dev/null"
  db:
    build: ./db/
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data:z
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
