version: '3'
services:
  go:
    build: ./go/
    command: bash -c "tail -f /dev/null"
    volumes:
      - ../:/root/my_contracts
    environment:
      DB_TEST_HOST: db
      DB_TEST_NAME: billing_test
      DB_TEST_USER: postgres
      DB_TEST_PASSWORD: password

      DB_DEVELOPMENT_HOST: db
      DB_DEVELOPMENT_NAME: billing_development
      DB_DEVELOPMENT_USER: postgres
      DB_DEVELOPMENT_PASSWORD: password

      DB_PRODUCTION_HOST: db
      DB_PRODUCTION_NAME: billing
      DB_PRODUCTION_USER: postgres
      DB_PRODUCTION_PASSWORD: password
    depends_on:
      - db

  db:
    build: ./db/
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data:z
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
