export DB_TEST_HOST=localhost
export DB_TEST_NAME=my_contracts_test
export DB_TEST_USER=postgres
export DB_TEST_PASSWORD=password

export DB_DEVELOPMENT_HOST=localhost
export DB_DEVELOPMENT_NAME=my_contracts_development
export DB_DEVELOPMENT_USER=postgres
export DB_DEVELOPMENT_PASSWORD=password

export DB_PRODUCTION_HOST=localhost
export DB_PRODUCTION_NAME=my_contracts
export DB_PRODUCTION_USER=postgres
export DB_PRODUCTION_PASSWORD=password
